name: "Multi Jest GitHub Action"
description: "Adds checks, annotations, and coverage comments to PRs with multiple Jest config files."
branding:
  icon: "check"
  color: "green"
inputs:
  test-command:
    description: "The test command to run"
    required: false
    default: "npm test"
  working-directory:
    description: "Subdirectory to run tests in"
    required: false
    default: ""
  coverage-comment:
    description: "Comment PRs with code coverage"
    required: false
    default: "true"
  changes-only:
    description: "Only run tests on changed files (over base branch)"
    required: false
    default: "false"
  config-file-name:
    description: "if you named your config file other than `jest.config.ts`, you can specify the name here"
    required: false
    default: "jest.config.ts"
  file-name:
    description: "if you named your test file other than `jest.results.json`, you can specify the name here"
    required: false
    default: "jest.results.json"
  test-name:
    description: "Name of your test to be displayed in the PR"
    required: false
    default: ""

runs:
  using: "node20"
  main: "dist/index.js"
