name: "Jest GitHub Action"
description: "Jest action adding checks and annotations to your pull requests and comment them with code coverage results."
branding:
  icon: "check"
  color: "green"
inputs:
  test-command:
    description: "The test command to run"
    required: false
    default: "npm test"
  working-directory:
    description: "Subdirectory to run tests in"
    required: false
    default: ""
  coverage-comment:
    description: "Comment PRs with code coverage"
    required: false
    default: "true"
  changes-only:
    description: "Only run tests on changed files (over base branch)"
    required: false
    default: "false"
  file-name:
    description: "if you name your test file other than `jest.results.json`, you can specify the name here"
    required: false
    default: "jest.results.json"
  result-name:
    description: "Name of the result file"
    required: false
    default: ""

runs:
  using: "node20"
  main: "dist/index.js"
